# Generated by Django 3.0.5 on 2021-06-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='location', max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('facility_nickname', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('hours_of_operation', models.CharField(max_length=100)),
                ('shifts', models.CharField(max_length=100)),
                ('use_case', models.CharField(max_length=100)),
                ('cgr', models.CharField(max_length=100)),
                ('subnet', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='organization', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('org', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='role', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='user', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
                ('roles', models.ManyToManyField(to='dataviewer.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='station_caregory_profile',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_type', models.CharField(max_length=100)),
                ('station_class', models.CharField(max_length=100)),
                ('station_model', models.CharField(max_length=100)),
                ('lanes', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.location')),
            ],
            options={
                'db_table': 'station_caregory_profile',
            },
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='resource', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.resource'),
        ),
        migrations.CreateModel(
            name='insight',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='insight', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('observations', models.CharField(max_length=100)),
                ('determinations', models.CharField(max_length=100)),
                ('metrics', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
            ],
            options={
                'db_table': 'insight',
            },
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='group', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='facility', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='device', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.resource')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='customer', max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(default='', max_length=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.resource')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('object_type', models.CharField(choices=[('contact', 'contact'), ('organization', 'organization'), ('insight', 'insight'), ('location', 'location'), ('resource', 'resource'), ('facility', 'facility'), ('role', 'role'), ('group', 'group'), ('user', 'user'), ('device', 'device')], default='contact', max_length=100)),
                ('contact_type', models.CharField(choices=[('business', 'business'), ('technical', 'technical'), ('administrative', 'administrative')], max_length=100)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.organization')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
