# Generated by Django 3.0.5 on 2021-04-27 05:20

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera_configs',
            fields=[
                ('config_id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=100, unique=True)),
                ('config_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='', max_length=100, null=True)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'camera_configs',
            },
        ),
        migrations.CreateModel(
            name='camera_group',
            fields=[
                ('group_id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('cameras', jsonfield.fields.JSONField(blank=True, default=[], null=True)),
            ],
            options={
                'db_table': 'camera_group',
            },
        ),
        migrations.CreateModel(
            name='camera_list',
            fields=[
                ('camera_id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('camera_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('camera_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='', max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'db_table': 'camera_list',
            },
        ),
    ]
