# Generated by Django 3.0.5 on 2021-04-27 05:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_group',
            name='cameras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
