# Generated by Django 3.0.5 on 2021-04-27 06:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_configuration', '0002_auto_20210427_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_configs',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
