# Generated by Django 3.0.5 on 2021-06-02 17:24

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_configuration', '0003_auto_20210427_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='incident_severity_mapping',
            fields=[
                ('camera_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='setup_configuration.camera_configs')),
                ('severity', models.CharField(max_length=100)),
                ('incident_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'incident_severity_mapping',
            },
        ),
        migrations.CreateModel(
            name='truck_details',
            fields=[
                ('truck_id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=100)),
                ('driver_id', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('truck_customer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'truck_details',
            },
        ),
        migrations.CreateModel(
            name='incident_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 6, 2, 22, 54, 23, 286401))),
                ('incident_type', models.CharField(blank=True, choices=[('Air Dusting', 'Air Dusting'), ('Cage Operation', 'Cage Operation'), ('PPE', 'PPE'), ('Track Allignment', 'Track Allignment')], default='', max_length=100, null=True)),
                ('severity', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), size=None)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_configuration.camera_list')),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_configuration.truck_details')),
            ],
            options={
                'db_table': 'incident_details',
            },
        ),
    ]
